version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3008:3306
    volumes:
      - my-db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
# Names our volume
volumes:
  my-db: